  env:
    node: true
  parser: '@typescript-eslint/parser'
  extends: 
    - 'plugin:@typescript-eslint/recommended'
  
  parserOptions: 
    ecmaVersion: 2018
    sourceType: module

  rules: 
    semi: error
    quotes: 
      - error
      - single
    '@typescript-eslint/explicit-function-return-type': off
    '@typescript-eslint/no-explicit-any': 1
    '@typescript-eslint/no-inferrable-types': 1
    '@typescript-eslint/no-unused-vars': warn
