env:
  node: true
extends:
  - 'airbnb'

plugins:
  - typescript
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'

rules:
  import/no-unresolved: 0
  import/prefer-default-export: 0
  typescript/no-unused-vars: warn
  # react/jsx-filename-extension:
  #     extensions:
  #       - '.jsx'
  #       - '.tsx'